<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sky" name="org.sky.auto.test.JUnitRemoteBaseTest" tests="3" failures="3" timestamp="28 Feb 2013 09:23:57 GMT" time="0.017" errors="0">
  <testcase name="methodTwo" time="0.007" classname="org.sky.auto.test.JUnitRemoteBaseTest">
    <failure type="java.lang.RuntimeException" message="org.databene.benerator.IllegalGeneratorStateException: Generation failed: ">
      <![CDATA[java.lang.RuntimeException: org.databene.benerator.IllegalGeneratorStateException: Generation failed: 
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:143)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:426)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.databene.benerator.IllegalGeneratorStateException: Generation failed: 
	at org.databene.benerator.wrapper.DataSourceGenerator.generate(DataSourceGenerator.java:103)
	at org.databene.benerator.wrapper.GeneratorWrapper.generateFromSource(GeneratorWrapper.java:69)
	at org.databene.benerator.wrapper.ConvertingGenerator.generate(ConvertingGenerator.java:76)
	at org.databene.benerator.wrapper.GeneratorWrapper.generateFromSource(GeneratorWrapper.java:69)
	at org.databene.benerator.wrapper.LastProductDetector.init(LastProductDetector.java:46)
	at org.databene.benerator.anno.AnnotationMapper.createAndInitMethodParamsGenerator(AnnotationMapper.java:176)
	at org.sky.auto.data.testng.excel.TestNGFeed.feeder(TestNGFeed.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
	... 9 more
Caused by: org.databene.commons.ConfigurationError: Resource not found: browser.xls
	at org.databene.commons.IOUtil.getResourceAsStream(IOUtil.java:561)
	at org.databene.commons.IOUtil.getFileOrResourceAsStream(IOUtil.java:548)
	at org.databene.commons.IOUtil.getInputStreamForURI(IOUtil.java:202)
	at org.databene.commons.IOUtil.getInputStreamForURI(IOUtil.java:186)
	at org.databene.document.xls.XLSLineIterator.sheet(XLSLineIterator.java:139)
	at org.databene.document.xls.XLSLineIterator.<init>(XLSLineIterator.java:67)
	at org.databene.document.xls.XLSLineIterator.<init>(XLSLineIterator.java:63)
	at org.databene.document.xls.XLSLineIterator.<init>(XLSLineIterator.java:59)
	at org.databene.document.xls.XLSSource.iterator(XLSSource.java:56)
	at org.databene.webdecs.util.DataSourceProxy.iterator(DataSourceProxy.java:40)
	at org.databene.webdecs.util.OffsetDataSource.iterator(OffsetDataSource.java:46)
	at org.databene.webdecs.util.ConvertingDataSource.iterator(ConvertingDataSource.java:51)
	at org.databene.benerator.wrapper.DataSourceGenerator.generate(DataSourceGenerator.java:95)
	... 21 more
]]>
    </failure>
  </testcase> <!-- methodTwo -->
  <testcase name="methodThree" time="0.009" classname="org.sky.auto.test.JUnitRemoteBaseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.sky.auto.window.Window.closeAllWindows(Window.java:121)
	at org.sky.auto.base.TestNGBase.destory(TestNGBase.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
]]>
    </failure>
  </testcase> <!-- methodThree -->
  <testcase name="methodOne" time="0.001" classname="org.sky.auto.test.JUnitRemoteBaseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.sky.auto.window.Window.closeAllWindows(Window.java:121)
	at org.sky.auto.base.TestNGBase.destory(TestNGBase.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
]]>
    </failure>
  </testcase> <!-- methodOne -->
</testsuite> <!-- org.sky.auto.test.JUnitRemoteBaseTest -->
